# Generated by Django 6.0.4 on 2026-04-18 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto')], default='ACTIVO', max_length=10)),
                ('condicion_entrega', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('DAÑADO', 'Dañado')], max_length=10)),
                ('observacion_entrega', models.TextField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('condicion_devolucion', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('DAÑADO', 'Dañado')], max_length=10, null=True)),
                ('presenta_danos', models.BooleanField(default=False)),
                ('observacion_devolucion', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipo.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
