# Generated by Django 5.2.7 on 2026-05-05 02:38

import apps.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.usuario.models.validate_email_catolica]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=8, validators=[apps.usuario.models.validate_telefono]),
        ),
    ]
