# Generated by Django 5.2.7 on 2026-05-09 00:07

import apps.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_prestatario_correo_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.usuario.models.validate_email_catolica]),
        ),
    ]
