# Generated by Django 6.0.4 on 2026-04-18 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('condicion_recepcion', models.CharField(max_length=100, verbose_name='Condición al Recibir')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Daños detectados')),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo', verbose_name='Préstamo Relacionado')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
    ]
