# Generated by Django 6.0.3 on 2026-04-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devolucion', '0001_initial'),
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='prestamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prestamo.prestamo'),
        ),
    ]
