# Generated by Django 5.2.7 on 2026-05-05 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato tipo PCA100 (letras seguidas de números).', regex='^[A-Z]+\\d+$')])),
                ('marca', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y números.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s]+$')])),
                ('modelo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y números.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s]+$')])),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de Inicio Mantenimiento')),
                ('fecha_mantenimiento_fin', models.DateField(verbose_name='Fecha de Fin Mantenimiento')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('MANTENIMIENTO', 'En mantenimiento'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
