# Generated by Django 5.2.7 on 2026-05-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_mantenimiento_fin',
        ),
    ]
