# Generated by Django 6.0.3 on 2026-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_USO', 'En uso'), ('MANTENIMIENTO', 'Mantenimiento'), ('FUERA', 'Fuera de servicio')], default='ACTIVO', max_length=15),
        ),
    ]
