# Generated by Django 6.0.4 on 2026-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_equipo_estado'),
        ('equipo', '0003_equipo_creado_por'),
    ]

    operations = [
    ]
