# Generated by Django 5.2.7 on 2026-05-05 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener 3 letras mayúsculas seguidas de 3 números (Ej: MAT123).', regex='^[A-Z]{3}\\d{3}$')], verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre solo permite letras, números y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s]+$')])),
                ('descripcion', models.TextField(validators=[django.core.validators.RegexValidator(message='La descripción solo puede contener letras, números y signos de puntuación.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\.,;\\-]+$')], verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
            ],
        ),
    ]
